### PR TITLE
Added legend image 

### LINKED ISSUE #56: Graph in Excel Export looks funny and needs legend
Two problems with the graph when exported into excel.  First, the dimensions are all off and look funny.  I assume that should be easy enough to fix by tweaking either the svgToPng sizing or something about where the images is added via `worksheet.addImage`.

The more important issue is that the legend did not come along because while the graph is an SVG that I embedded, the legend is not.  If we can pull it in dynamically via some embedded html or something fancy, that's cool, but if not the legend is static and i'm totally happy with just either recreating it in excel or just taking a screenshot and embedding that.

For dev expediency, I would change the `NUM_YEARS_TO_RUN` variable in config.ts to something small so you don't have to run the full years every time, maybe just 1 year.

### PR DESCRIPTION
**Pull request by wongband**
closes #56

### CODE REVIEW

**Review by srkirkland — CHANGES_REQUESTED** [review]
@wongband please revert the changes to config.ts

**Comment by wongband** [comment]
@srkirkland whoops, sorry about that

**Comment by srkirkland** [comment]
@wongband It looks like you included the chart image but then never used it, instead using the base64 string of that image.  I'm assuming you tried 
```
const imageId1 = workbook.addImage({
  filename: 'path/to/image.jpg',
  extension: 'jpeg',
});
```
and there was some problem?  It seems like that would be a better option.

**Comment by wongband** [comment]
@srkirkland I kept getting this error, `Uncaught (in promise) TypeError: u.readFile is not a function` and was not sure how to resolve it

**Comment by srkirkland** [comment]
@wongband Ok I'll take a quick look at this later today.  Otherwise the PR looks good!

**Comment by srkirkland** [comment]
@wongband ok I think I like your base64 method but please delete the image and then move the base64 string to another new file and export it as a variable so that it is not inline.

**Review by srkirkland — APPROVED** [review]

**Pull request merged**
